// MERIDIAN read API. Read-only by construction: this service has exactly
// three unary methods and none of them writes. A write path would drag
// transport into P1's at-most-once claim (design Q5, 2026-08-31).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: meridian/v1/read.proto

package meridianv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reader_Head_FullMethodName      = "/meridian.v1.Reader/Head"
	Reader_AsOf_FullMethodName      = "/meridian.v1.Reader/AsOf"
	Reader_Reconcile_FullMethodName = "/meridian.v1.Reader/Reconcile"
)

// ReaderClient is the client API for Reader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReaderClient interface {
	// Head returns the feed length and the prefix hash of the whole feed
	// (what `meridian replay` prints).
	Head(ctx context.Context, in *HeadRequest, opts ...grpc.CallOption) (*HeadResponse, error)
	// AsOf replays the prefix [1..seq] and returns the canonical snapshot
	// bytes verbatim plus their sha256. seq < 0 means end of feed.
	AsOf(ctx context.Context, in *AsOfRequest, opts ...grpc.CallOption) (*AsOfResponse, error)
	// Reconcile compares the snapshot at seq with a custodian statement
	// (the same JSON bytes `meridian reconcile --statement` loads).
	Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileResponse, error)
}

type readerClient struct {
	cc grpc.ClientConnInterface
}

func NewReaderClient(cc grpc.ClientConnInterface) ReaderClient {
	return &readerClient{cc}
}

func (c *readerClient) Head(ctx context.Context, in *HeadRequest, opts ...grpc.CallOption) (*HeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeadResponse)
	err := c.cc.Invoke(ctx, Reader_Head_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerClient) AsOf(ctx context.Context, in *AsOfRequest, opts ...grpc.CallOption) (*AsOfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AsOfResponse)
	err := c.cc.Invoke(ctx, Reader_AsOf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerClient) Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileResponse)
	err := c.cc.Invoke(ctx, Reader_Reconcile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReaderServer is the server API for Reader service.
// All implementations must embed UnimplementedReaderServer
// for forward compatibility.
type ReaderServer interface {
	// Head returns the feed length and the prefix hash of the whole feed
	// (what `meridian replay` prints).
	Head(context.Context, *HeadRequest) (*HeadResponse, error)
	// AsOf replays the prefix [1..seq] and returns the canonical snapshot
	// bytes verbatim plus their sha256. seq < 0 means end of feed.
	AsOf(context.Context, *AsOfRequest) (*AsOfResponse, error)
	// Reconcile compares the snapshot at seq with a custodian statement
	// (the same JSON bytes `meridian reconcile --statement` loads).
	Reconcile(context.Context, *ReconcileRequest) (*ReconcileResponse, error)
	mustEmbedUnimplementedReaderServer()
}

// UnimplementedReaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReaderServer struct{}

func (UnimplementedReaderServer) Head(context.Context, *HeadRequest) (*HeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Head not implemented")
}
func (UnimplementedReaderServer) AsOf(context.Context, *AsOfRequest) (*AsOfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AsOf not implemented")
}
func (UnimplementedReaderServer) Reconcile(context.Context, *ReconcileRequest) (*ReconcileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconcile not implemented")
}
func (UnimplementedReaderServer) mustEmbedUnimplementedReaderServer() {}
func (UnimplementedReaderServer) testEmbeddedByValue()                {}

// UnsafeReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReaderServer will
// result in compilation errors.
type UnsafeReaderServer interface {
	mustEmbedUnimplementedReaderServer()
}

func RegisterReaderServer(s grpc.ServiceRegistrar, srv ReaderServer) {
	// If the following call panics, it indicates UnimplementedReaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reader_ServiceDesc, srv)
}

func _Reader_Head_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServer).Head(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reader_Head_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServer).Head(ctx, req.(*HeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reader_AsOf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServer).AsOf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reader_AsOf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServer).AsOf(ctx, req.(*AsOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reader_Reconcile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServer).Reconcile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reader_Reconcile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServer).Reconcile(ctx, req.(*ReconcileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Reader_ServiceDesc is the grpc.ServiceDesc for Reader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.v1.Reader",
	HandlerType: (*ReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Head",
			Handler:    _Reader_Head_Handler,
		},
		{
			MethodName: "AsOf",
			Handler:    _Reader_AsOf_Handler,
		},
		{
			MethodName: "Reconcile",
			Handler:    _Reader_Reconcile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meridian/v1/read.proto",
}
