// MERIDIAN read API. Read-only by construction: this service has exactly
// three unary methods and none of them writes. A write path would drag
// transport into P1's at-most-once claim (design Q5, 2026-08-31).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: meridian/v1/read.proto

package meridianv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadRequest) Reset() {
	*x = HeadRequest{}
	mi := &file_meridian_v1_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadRequest) ProtoMessage() {}

func (x *HeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_v1_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadRequest.ProtoReflect.Descriptor instead.
func (*HeadRequest) Descriptor() ([]byte, []int) {
	return file_meridian_v1_read_proto_rawDescGZIP(), []int{0}
}

type HeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       int64                  `protobuf:"varint,1,opt,name=records,proto3" json:"records,omitempty"`
	PrefixHash    string                 `protobuf:"bytes,2,opt,name=prefix_hash,json=prefixHash,proto3" json:"prefix_hash,omitempty"` // "sha256:<hex>"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadResponse) Reset() {
	*x = HeadResponse{}
	mi := &file_meridian_v1_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadResponse) ProtoMessage() {}

func (x *HeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_v1_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadResponse.ProtoReflect.Descriptor instead.
func (*HeadResponse) Descriptor() ([]byte, []int) {
	return file_meridian_v1_read_proto_rawDescGZIP(), []int{1}
}

func (x *HeadResponse) GetRecords() int64 {
	if x != nil {
		return x.Records
	}
	return 0
}

func (x *HeadResponse) GetPrefixHash() string {
	if x != nil {
		return x.PrefixHash
	}
	return ""
}

type AsOfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // < 0 means end of feed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsOfRequest) Reset() {
	*x = AsOfRequest{}
	mi := &file_meridian_v1_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsOfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsOfRequest) ProtoMessage() {}

func (x *AsOfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_v1_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsOfRequest.ProtoReflect.Descriptor instead.
func (*AsOfRequest) Descriptor() ([]byte, []int) {
	return file_meridian_v1_read_proto_rawDescGZIP(), []int{2}
}

func (x *AsOfRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type AsOfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                                      // resolved seq (a -1 request answers with the real end seq)
	PrefixHash    string                 `protobuf:"bytes,2,opt,name=prefix_hash,json=prefixHash,proto3" json:"prefix_hash,omitempty"`       // "sha256:<hex>" of the feed prefix [1..seq]
	SnapshotHash  string                 `protobuf:"bytes,3,opt,name=snapshot_hash,json=snapshotHash,proto3" json:"snapshot_hash,omitempty"` // "sha256:<hex>" over `snapshot` exactly as sent
	Snapshot      []byte                 `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`                             // canonical JSON + '\n', byte-identical to `meridian asof`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsOfResponse) Reset() {
	*x = AsOfResponse{}
	mi := &file_meridian_v1_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsOfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsOfResponse) ProtoMessage() {}

func (x *AsOfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_v1_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsOfResponse.ProtoReflect.Descriptor instead.
func (*AsOfResponse) Descriptor() ([]byte, []int) {
	return file_meridian_v1_read_proto_rawDescGZIP(), []int{3}
}

func (x *AsOfResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AsOfResponse) GetPrefixHash() string {
	if x != nil {
		return x.PrefixHash
	}
	return ""
}

func (x *AsOfResponse) GetSnapshotHash() string {
	if x != nil {
		return x.SnapshotHash
	}
	return ""
}

func (x *AsOfResponse) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type ReconcileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Statement     []byte                 `protobuf:"bytes,2,opt,name=statement,proto3" json:"statement,omitempty"` // custodian statement JSON object
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_meridian_v1_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_v1_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_meridian_v1_read_proto_rawDescGZIP(), []int{4}
}

func (x *ReconcileRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ReconcileRequest) GetStatement() []byte {
	if x != nil {
		return x.Statement
	}
	return nil
}

type Mismatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instrument    string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"` // empty for the cash field
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`           // "cash" | "quantity" | "cost_basis"
	Ledger        int64                  `protobuf:"varint,3,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Custodian     int64                  `protobuf:"varint,4,opt,name=custodian,proto3" json:"custodian,omitempty"`
	Delta         int64                  `protobuf:"varint,5,opt,name=delta,proto3" json:"delta,omitempty"` // ledger - custodian
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mismatch) Reset() {
	*x = Mismatch{}
	mi := &file_meridian_v1_read_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mismatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mismatch) ProtoMessage() {}

func (x *Mismatch) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_v1_read_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mismatch.ProtoReflect.Descriptor instead.
func (*Mismatch) Descriptor() ([]byte, []int) {
	return file_meridian_v1_read_proto_rawDescGZIP(), []int{5}
}

func (x *Mismatch) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *Mismatch) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Mismatch) GetLedger() int64 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

func (x *Mismatch) GetCustodian() int64 {
	if x != nil {
		return x.Custodian
	}
	return 0
}

func (x *Mismatch) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type ReconcileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compared      int64                  `protobuf:"varint,1,opt,name=compared,proto3" json:"compared,omitempty"`
	Mismatches    []*Mismatch            `protobuf:"bytes,2,rep,name=mismatches,proto3" json:"mismatches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileResponse) Reset() {
	*x = ReconcileResponse{}
	mi := &file_meridian_v1_read_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResponse) ProtoMessage() {}

func (x *ReconcileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meridian_v1_read_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResponse.ProtoReflect.Descriptor instead.
func (*ReconcileResponse) Descriptor() ([]byte, []int) {
	return file_meridian_v1_read_proto_rawDescGZIP(), []int{6}
}

func (x *ReconcileResponse) GetCompared() int64 {
	if x != nil {
		return x.Compared
	}
	return 0
}

func (x *ReconcileResponse) GetMismatches() []*Mismatch {
	if x != nil {
		return x.Mismatches
	}
	return nil
}

var File_meridian_v1_read_proto protoreflect.FileDescriptor

const file_meridian_v1_read_proto_rawDesc = "" +
	"\n" +
	"\x16meridian/v1/read.proto\x12\vmeridian.v1\"\r\n" +
	"\vHeadRequest\"I\n" +
	"\fHeadResponse\x12\x18\n" +
	"\arecords\x18\x01 \x01(\x03R\arecords\x12\x1f\n" +
	"\vprefix_hash\x18\x02 \x01(\tR\n" +
	"prefixHash\"\x1f\n" +
	"\vAsOfRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\"\x82\x01\n" +
	"\fAsOfResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x1f\n" +
	"\vprefix_hash\x18\x02 \x01(\tR\n" +
	"prefixHash\x12#\n" +
	"\rsnapshot_hash\x18\x03 \x01(\tR\fsnapshotHash\x12\x1a\n" +
	"\bsnapshot\x18\x04 \x01(\fR\bsnapshot\"B\n" +
	"\x10ReconcileRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x1c\n" +
	"\tstatement\x18\x02 \x01(\fR\tstatement\"\x8c\x01\n" +
	"\bMismatch\x12\x1e\n" +
	"\n" +
	"instrument\x18\x01 \x01(\tR\n" +
	"instrument\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x16\n" +
	"\x06ledger\x18\x03 \x01(\x03R\x06ledger\x12\x1c\n" +
	"\tcustodian\x18\x04 \x01(\x03R\tcustodian\x12\x14\n" +
	"\x05delta\x18\x05 \x01(\x03R\x05delta\"f\n" +
	"\x11ReconcileResponse\x12\x1a\n" +
	"\bcompared\x18\x01 \x01(\x03R\bcompared\x125\n" +
	"\n" +
	"mismatches\x18\x02 \x03(\v2\x15.meridian.v1.MismatchR\n" +
	"mismatches2\xce\x01\n" +
	"\x06Reader\x12;\n" +
	"\x04Head\x12\x18.meridian.v1.HeadRequest\x1a\x19.meridian.v1.HeadResponse\x12;\n" +
	"\x04AsOf\x12\x18.meridian.v1.AsOfRequest\x1a\x19.meridian.v1.AsOfResponse\x12J\n" +
	"\tReconcile\x12\x1d.meridian.v1.ReconcileRequest\x1a\x1e.meridian.v1.ReconcileResponseB?Z=github.com/hossainpazooki/meridian/api/meridian/v1;meridianv1b\x06proto3"

var (
	file_meridian_v1_read_proto_rawDescOnce sync.Once
	file_meridian_v1_read_proto_rawDescData []byte
)

func file_meridian_v1_read_proto_rawDescGZIP() []byte {
	file_meridian_v1_read_proto_rawDescOnce.Do(func() {
		file_meridian_v1_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meridian_v1_read_proto_rawDesc), len(file_meridian_v1_read_proto_rawDesc)))
	})
	return file_meridian_v1_read_proto_rawDescData
}

var file_meridian_v1_read_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_meridian_v1_read_proto_goTypes = []any{
	(*HeadRequest)(nil),       // 0: meridian.v1.HeadRequest
	(*HeadResponse)(nil),      // 1: meridian.v1.HeadResponse
	(*AsOfRequest)(nil),       // 2: meridian.v1.AsOfRequest
	(*AsOfResponse)(nil),      // 3: meridian.v1.AsOfResponse
	(*ReconcileRequest)(nil),  // 4: meridian.v1.ReconcileRequest
	(*Mismatch)(nil),          // 5: meridian.v1.Mismatch
	(*ReconcileResponse)(nil), // 6: meridian.v1.ReconcileResponse
}
var file_meridian_v1_read_proto_depIdxs = []int32{
	5, // 0: meridian.v1.ReconcileResponse.mismatches:type_name -> meridian.v1.Mismatch
	0, // 1: meridian.v1.Reader.Head:input_type -> meridian.v1.HeadRequest
	2, // 2: meridian.v1.Reader.AsOf:input_type -> meridian.v1.AsOfRequest
	4, // 3: meridian.v1.Reader.Reconcile:input_type -> meridian.v1.ReconcileRequest
	1, // 4: meridian.v1.Reader.Head:output_type -> meridian.v1.HeadResponse
	3, // 5: meridian.v1.Reader.AsOf:output_type -> meridian.v1.AsOfResponse
	6, // 6: meridian.v1.Reader.Reconcile:output_type -> meridian.v1.ReconcileResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meridian_v1_read_proto_init() }
func file_meridian_v1_read_proto_init() {
	if File_meridian_v1_read_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meridian_v1_read_proto_rawDesc), len(file_meridian_v1_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meridian_v1_read_proto_goTypes,
		DependencyIndexes: file_meridian_v1_read_proto_depIdxs,
		MessageInfos:      file_meridian_v1_read_proto_msgTypes,
	}.Build()
	File_meridian_v1_read_proto = out.File
	file_meridian_v1_read_proto_goTypes = nil
	file_meridian_v1_read_proto_depIdxs = nil
}
